---
title: "Cesium Use plots"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Plot and predict Cesium use based on reservoir mass.

* TODO: add data for CFAMS
* TODO: calculate days since new Cs
* TODO: calculate res mass from initial mass
* TODO: calculate use per target
* TODO: Refactor


```{r}
library(tidyverse)
library(lubridate)
library(amstools)

# set plotting theme
theme_set(theme_light())
```

```{r}
cs <- read_csv("cesium.csv") %>%
  mutate(Date = mdy(Date))

runnum <- 0
for (row in 1:nrow(cs)) {
        if (cs[row,"NewCs"] == TRUE) {
                runnum <- runnum + 1
                sd <- cs[row, "Date"]
                initmass <- cs[row, "Mass"]
        }
        cs[row, "No"] <- runnum
        cs[row, "startdate"] <- sd
        cs[row, "CsMass"] <- initmass + 5 - cs[row, "Mass"]
}

cs <- cs %>%
  mutate(CsMass = ifelse(Mass > 400, Mass - 406.8, Mass - 393.3),
         et = Date - startdate,
         No = as.factor(No))

cs$runs = mapply(numRun, cs$startdate, cs$Date, "USAMS")[1,]
```

```{r}
cs.lm <- lm(CsMass ~ et, data = cs)
cs.lm
use <- abs(coef(cs.lm)["et"])
use5 <- 5 / use 
```

Average use rate is `r round(use, 2)` g per day. Thats `r round(use5)` days per charge.

```{r}
ggplot(cs, aes(et, CsMass, color = No)) +
  geom_smooth(method = "lm", fullrange = TRUE) +
  geom_point() +
  ylim(0,5) +
  scale_colour_brewer(type = "div", palette = "Set2") +
  labs(title = "USAMS Cesium use over time",
       x = "Days", y = "Cesium mass (g)")

ggplot(cs, aes(runs, CsMass, color = No)) +
  geom_smooth(method = "lm", fullrange = TRUE) +
  geom_point(size = 3) + ylim(0,5) +
  scale_colour_brewer(type = "div", palette = "Set2") +
  labs(title = "USAMS Cesium use per target",
       x = "Targets run", y = "Cesium mass (g)")
```
